export default {
  gallery: document.querySelector('#gallery'),
  libary: document.querySelector('#libary'),
  homeBtn: document.querySelector('#homeBtn'),
  libaryBtn: document.querySelector('#libaryBtn'),
  form: document.querySelector('#form'),
  libaryOptions: document.querySelector('#libaryOptions'),
  decrementBtn: document.querySelector('#decrementBtn'),
  incrementBtn: document.querySelector('#incrementBtn'),
  card: document.querySelector('.gallery__item'),
  backdrop: document.querySelector('#backdrop'),
  closeModal: document.querySelector('#close-modal'),
  addToQueue: document.querySelector('#add-to-queue'),
  addWached: document.querySelector('#add-wached'),
};
