export default {
  gallery: document.querySelector('.gallery'),
  pagination: document.querySelector('.pagination'),
  libary: document.querySelector('.libary'),
  homeBtn: document.querySelector('.header__btn-home'),
  libaryBtn: document.querySelector('.header__btn-libary'),
  form: document.querySelector('.form'),
  libaryOptions: document.querySelector('.libary__options'),
  decrementBtn: document.querySelector('.prew-btn'),
  incrementBtn: document.querySelector('.next-btn'),
  backdrop: document.querySelector('.backdrop'),
  addToQueue: null,
  addWached: null,
  pageNumberBox: document.querySelector('.page-number-box'),
  currentPageNumber: document.querySelector('.current-page-namber'),
  totalpageNumber: document.querySelector('.total-page-number'),
};
